"""
AI Portfolio Backend API
------------------------
This FastAPI service acts as the orchestration layer for the AI Portfolio.
It handles semantic search (RAG) via Supabase pgvector, LLM inference via Groq,
and enforces deterministic structured outputs using Pydantic and a self-correction retry loop.

Author: Gustavo Valentim
"""

import os
import logging
import httpx
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, Request, BackgroundTasks
from pydantic import BaseModel, Field, ValidationError
from supabase import create_client
from openai import OpenAI
from groq import Groq
from fastapi.middleware.cors import CORSMiddleware
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded

# Set up internal logging for monitoring production errors
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Load environment variables (API keys are NEVER hardcoded)
load_dotenv()

# Initialize API Clients
supabase = create_client(os.getenv("SUPABASE_URL"), os.getenv("SUPABASE_KEY"))
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))

# Initialize Rate Limiter (IP-based) to protect cloud resources
limiter = Limiter(key_func=get_remote_address)

app = FastAPI(title="Gustavo Portfolio API - Production")
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

# ==========================================
# SECURITY: Strict CORS Configuration
# ==========================================
# We only allow requests explicitly originating from the Vercel frontend.
# This prevents unauthorized domains from hijacking the API and burning LLM credits.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["https://gustavo-valentim.vercel.app"], 
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ==========================================
# DATA MODELS (Pydantic Validation Layer)
# ==========================================
class ChatMessage(BaseModel):
    role: str
    content: str

class QueryRequest(BaseModel):
    question: str = Field(..., max_length=500, description="The user's question")
    history: list[ChatMessage] = [] 

class QueryResponse(BaseModel):
    """The standard format sent back to the React frontend."""
    answer: str
    sources: list[str]

class LLMResponse(BaseModel):
    """
    Strict schema to enforce deterministic output from the LLM.
    If the LLM hallucinates a different JSON structure, Pydantic will raise a ValidationError.
    """
    answer: str = Field(..., description="The answer generated by the LLM based on the context and question.")

class ContactRequest(BaseModel):
    name: str = Field(..., max_length=100)
    email: str = Field(..., max_length=150)
    message: str = Field(..., max_length=1000)


# ==========================================
# HELPER FUNCTIONS
# ==========================================
def embed_query(text: str):
    """Generates a vector embedding for the user's question using OpenAI."""
    response = client.embeddings.create(
        model="text-embedding-3-small",
        input=text
    )
    return response.data[0].embedding

def send_notification_email(name: str, user_email: str, message: str):
    """Asynchronously sends an email notification via the Resend API."""
    resend_api_key = os.getenv("RESEND_API_KEY")
    my_email = os.getenv("EMAIL_USER") 

    if not resend_api_key or not my_email:
        logger.warning("Resend API key missing. Contact saved to DB, but email skipped.")
        return

    headers = {
        "Authorization": f"Bearer {resend_api_key}",
        "Content-Type": "application/json"
    }

    payload = {
        "from": "Portfolio Agent <onboarding@resend.dev>",
        "to": my_email,
        "subject": f"🚀 New Portfolio Contact: {name}",
        "html": f"""
        <h2>You have a new message from your portfolio!</h2>
        <p><strong>Name:</strong> {name}</p>
        <p><strong>Email:</strong> {user_email}</p>
        <p><strong>Message:</strong></p>
        <blockquote style="border-left: 4px solid #ccc; padding-left: 10px;">{message}</blockquote>
        <br>
        <p><em>Note: Just click 'Reply' to email them back directly!</em></p>
        """,
        "reply_to": user_email
    }

    try:
        with httpx.Client() as http_client:
            response = http_client.post("https://api.resend.com/emails", json=payload, headers=headers)
            response.raise_for_status()
            logger.info("Email sent successfully via Resend API!")
    except Exception as e:
        logger.error(f"Failed to send email via Resend: {e}")


# ==========================================
# API ENDPOINTS
# ==========================================

@app.post("/api/ask", response_model=QueryResponse)
@limiter.limit("3/minute")
async def ask_portfolio(request: Request, query: QueryRequest):
    """
    The core RAG Orchestration Endpoint.
    1. Embeds the query.
    2. Performs vector search in Supabase.
    3. Prompts the LLM with strict JSON constraints.
    4. Validates output and implements a self-correction loop for hallucinations.
    """
    try:
        # 1. Retrieval (Vector Search)
        query_embedding = embed_query(query.question)
        response = supabase.rpc(
            "match_documents",
            {
                "query_embedding": query_embedding,
                "match_count": 4
            }
        ).execute()

        results = response.data
        if not results:
            return QueryResponse(answer="I don't have that specific information in my context right now, but I am always happy to discuss my background directly!", sources=[])

        # 2. Reranking (Importance-weighted)
        reranked = []
        for doc in results:
            weight = doc["metadata"].get("importance_weight", 1.0)
            final_score = doc["similarity"] * weight
            reranked.append((final_score, doc))

        reranked.sort(reverse=True, key=lambda x: x[0])

        context_blocks = []
        source_list = []
        for score, doc in reranked:
            source_name = doc['metadata']['source']
            context_blocks.append(f"--- Source: {source_name} ---\n{doc['content']}")
            if source_name not in source_list:
                source_list.append(source_name)

        context_text = "\n\n".join(context_blocks)

        # 3. Prompt Engineering (Enforcing JSON format)
        system_prompt = """You are Gustavo's personal AI advocate — think of yourself as his most enthusiastic professional wingman. 

                🎯 YOUR CORE MISSION:
                Sell Gustavo. Confidently. Warmly. Authentically.
                Make the person on the other side think: "I need to talk to this guy."

                👤 WHO IS GUSTAVO:
                - AI Engineer with 5+ years of experience across multiple technical domains
                - Exceptional problem solver who finds elegant solutions where others see dead ends
                - Actively and eagerly looking for his next big challenge 🚀

                📋 STRICT RULES:
                1. Base ALL claims ONLY on the provided context — never invent experience.
                2. Never say "I don't know" coldly — always redirect with energy.
        
                ⚠️ JSON OUTPUT FORMAT RULE ⚠️
                You MUST return your response exclusively in valid JSON format. 
                The JSON must contain exactly one key called "answer" containing your final text response.
                Do not add markdown formatting, do not add explanations outside the JSON.
                """

        groq_messages = [{"role": "system", "content": system_prompt}]
        
        # Inject conversation history
        for msg in query.history[-3:]:
            clean_content = msg.content.split("Sources:")[0].strip()
            groq_messages.append({"role": msg.role, "content": clean_content})

        groq_messages.append({
            "role": "user", 
            "content": f"Context information is below.\n\n{context_text}\n\nQuestion: {query.question}"
        })
        
        # 4. Inference & Autonomous Self-Correction Loop
        max_retries = 3
        for attempt in range(max_retries):
            try:
                # Force JSON generation
                chat_completion = groq_client.chat.completions.create(
                    messages=groq_messages,
                    model="llama-3.3-70b-versatile",
                    temperature=0.3,
                    response_format={"type": "json_object"}
                )
                raw_json_string = chat_completion.choices[0].message.content
                
                # Strict Schema Validation: This acts as a firewall. 
                # If the LLM hallucinates the structure, this raises a ValidationError.
                validated_llm_data = LLMResponse.model_validate_json(raw_json_string)
                
                return QueryResponse(
                    answer=validated_llm_data.answer,
                    sources=source_list
                )
                
            except Exception as e:
                logger.warning(f"Attempt {attempt+1} - LLM Hallucinated Format: {str(e)}. Retrying...")
                
                # Graceful degradation if the LLM fails after 3 attempts
                if attempt == max_retries - 1:
                    logger.error(f"Failed to get a valid response after {max_retries} attempts. Returning fallback.")
                    return QueryResponse(
                        answer="I had a bit of trouble formulating a response based on the context, but I can assure you Gustavo is an exceptional AI Engineer. Feel free to use the contact tab!",
                        sources=source_list)
                
                # Self-Correction Mechanism: Feed the error back to the LLM so it learns and fixes it.
                groq_messages.append({"role": "assistant", "content": raw_json_string})
                groq_messages.append({
                    "role": "user", 
                    "content": f"The previous response failed validation. You MUST fix the formatting. Detail: {str(e)}"
                })

    except Exception as e:
        logger.error(f"Error processing request: {str(e)}")
        raise HTTPException(status_code=500, detail="Internal server error. Please try again later.")


@app.post("/api/contact")
@limiter.limit("2/hour") 
async def submit_contact(request: Request, contact: ContactRequest, background_tasks: BackgroundTasks):
    """Handles contact form submissions, saving to DB and sending email async."""
    try:
        supabase.table("contacts").insert({
            "name": contact.name,
            "email": contact.email,
            "message": contact.message
        }).execute()

        background_tasks.add_task(send_notification_email, contact.name, contact.email, contact.message)
        return {"status": "success", "message": "Message received! I will get back to you soon."}

    except Exception as e:
        logger.error(f"Error saving contact: {str(e)}")
        raise HTTPException(status_code=500, detail="Failed to send message.")